# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=11)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('date_regis', models.DateField()),
                ('section', models.CharField(max_length=5)),
                ('subject', models.CharField(max_length=50)),
                ('teacher', models.CharField(max_length=100)),
                ('attendance_point', models.IntegerField()),
                ('collect_point', models.IntegerField()),
                ('test_point', models.IntegerField()),
            ],
        ),
    ]
