# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 08:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend_times', models.IntegerField(default=None)),
                ('absent_times', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_point', models.IntegerField(default=None)),
                ('mental_point', models.IntegerField(default=None)),
                ('collect_point', models.IntegerField(default=None)),
                ('midterm_point', models.IntegerField(default=None)),
                ('final_point', models.IntegerField(default=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='attendance_point',
        ),
        migrations.RemoveField(
            model_name='student',
            name='collect_point',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='test_point',
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='birthday',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='id_number',
            field=models.CharField(default=None, max_length=13),
        ),
        migrations.AddField(
            model_name='student',
            name='main_subject',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='teacher_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='teacher_subject',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='telephone',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_regis',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastname',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=None, max_length=11),
        ),
        migrations.AddField(
            model_name='scores',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.Student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.Student'),
        ),
    ]
