# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_auto_20161112_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='absent_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attend_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scores',
            name='attendance_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scores',
            name='collect_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scores',
            name='final_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scores',
            name='mental_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scores',
            name='midterm_point',
            field=models.IntegerField(default=0),
        ),
    ]
